version: '3'
services:
  postgres:
    image: postgres:alpine3.19
    container_name: covoiturage-db
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./bdd/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
    - POSTGRES_DB=covoiturage
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    ports:
      - 5431:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  back:
    build: ./back
    ports:
      - 8080:8080
    depends_on:
      - postgres
    secrets:
      - db-password
    environment:
      - PORT=8080
      - DB_USER=postgres
      - DB_HOST=postgres
      - DB_DATABASE=covoiturage
      - DB_PASSWORD=root
      - DB_PORT=5432
  # front:
  #   build: ./front
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - back
  #   environment:
  #     - REACT_APP_API_URL=http://localhost:8080
volumes:
  db-data:
secrets:
  db-password:
    file: bdd/password.txt